"""optimize_and_document_tables

Revision ID: 264963ca7e56
Revises: 
Create Date: 2026-07-18 17:16:04.010066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '264963ca7e56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companion_memories', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('companion_memories', 'memory_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Category: core_belief, event, preference, etc.',
               existing_nullable=False)
    op.alter_column('companion_memories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_companion_memories_user_id'), 'companion_memories', ['user_id'], unique=False)
    op.create_table_comment(
        'companion_memories',
        'Extracted context that the AI should remember over time',
        existing_comment=None,
        schema=None
    )
    op.add_column('consultation_notes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('consultation_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_table_comment(
        'consultation_notes',
        'AI-generated summary and insights for a session',
        existing_comment=None,
        schema=None
    )
    op.add_column('message_emotions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('message_emotions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('message_emotions', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Confidence score of the emotion model',
               existing_nullable=False)
    op.create_table_comment(
        'message_emotions',
        'Emotion classification for a specific message',
        existing_comment=None,
        schema=None
    )
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='Speaker role: user, assistant, system',
               existing_nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table_comment(
        'messages',
        'Individual messages within a conversation session',
        existing_comment=None,
        schema=None
    )
    op.add_column('risk_logs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('risk_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_risk_logs_session_id'), 'risk_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_risk_logs_user_id'), 'risk_logs', ['user_id'], unique=False)
    op.create_table_comment(
        'risk_logs',
        'Audit logs of times the system detected high-risk user input',
        existing_comment=None,
        schema=None
    )
    op.add_column('session_feedbacks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('session_feedbacks', 'rating',
               existing_type=sa.INTEGER(),
               comment='Rating from 1 to 5',
               existing_nullable=False)
    op.alter_column('session_feedbacks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_table_comment(
        'session_feedbacks',
        'User feedback ratings for a session',
        existing_comment=None,
        schema=None
    )
    op.add_column('sessions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('sessions', 'ended_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('sessions', 'channel',
               existing_type=sa.VARCHAR(length=20),
               comment='Interface used: web, voice, mobile',
               existing_nullable=True)
    op.alter_column('sessions', 'is_crisis_flagged',
               existing_type=sa.BOOLEAN(),
               comment='True if any message in this session triggered crisis detection',
               existing_nullable=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table_comment(
        'sessions',
        'Conversation sessions between user and the companion',
        existing_comment=None,
        schema=None
    )
    op.add_column('user_goals', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user_goals', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Expected values: in_progress, achieved, abandoned',
               existing_nullable=True)
    op.alter_column('user_goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('user_goals', 'target_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_user_goals_user_id'), 'user_goals', ['user_id'], unique=False)
    op.create_table_comment(
        'user_goals',
        'Therapeutic goals set by the user',
        existing_comment=None,
        schema=None
    )
    op.add_column('user_journals', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user_journals', 'mood',
               existing_type=sa.VARCHAR(length=30),
               comment='Mood associated with the entry',
               existing_nullable=True)
    op.alter_column('user_journals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_user_journals_user_id'), 'user_journals', ['user_id'], unique=False)
    op.create_table_comment(
        'user_journals',
        'Reflective journal entries written by the user',
        existing_comment=None,
        schema=None
    )
    op.add_column('user_preferences', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user_preferences', 'theme',
               existing_type=sa.VARCHAR(length=20),
               comment='UI Theme (light, dark, system)',
               existing_nullable=True)
    op.create_table_comment(
        'user_preferences',
        'App settings and interface preferences',
        existing_comment=None,
        schema=None
    )
    op.add_column('user_profiles', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user_profiles', 'bio',
               existing_type=sa.TEXT(),
               comment='User-provided biographical context',
               existing_nullable=True)
    op.alter_column('user_profiles', 'preferred_name',
               existing_type=sa.VARCHAR(length=50),
               comment='Name the AI should use to address the user',
               existing_nullable=True)
    op.alter_column('user_profiles', 'therapy_focus',
               existing_type=sa.VARCHAR(length=100),
               comment='Main focus area (e.g. anxiety, relationships)',
               existing_nullable=True)
    op.create_table_comment(
        'user_profiles',
        'Extended personal and therapeutic profile details',
        existing_comment=None,
        schema=None
    )
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Last modification timestamp'))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique handle chosen by the user',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               comment='User email for login and recovery',
               existing_nullable=False)
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(length=10),
               comment='Language code like en-IN, hi-IN, te-IN, ta-IN',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='When the user account was created',
               existing_nullable=True)
    op.create_table_comment(
        'users',
        'Core user table storing authentication and base preferences',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
